package me.uoken.haiku;

import me.uoken.haiku.command.HaikuCommand;
import me.uoken.haiku.gui.HaikuGuiScreen;
import me.uoken.haiku.gui.HaikuGuiScreenSecond;
import me.uoken.haiku.util.ConfigUtil;
import me.uoken.haiku.util.HaikuThreadFactory;
import net.minecraft.client.Minecraft;
import net.minecraft.util.text.ITextComponent;
import net.minecraftforge.client.ClientCommandHandler;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;
import net.minecraftforge.fml.common.network.FMLNetworkEvent;

//import java.util.ArrayList;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.MOD_VERSION, acceptedMinecraftVersions = Reference.MC_VERSION, clientSideOnly = true, useMetadata = true)
public class Haiku {
    private final Minecraft mc = Minecraft.getMinecraft();
    private int countBuff = 0;
    private int countRanking = 0;
    private static Haiku instance;
    private ITextComponent addChatMessage;
    public static final ExecutorService THREAD_POOL;
    private boolean showBuffCounter = true, showRankingCounter = true;
    private boolean showGui = false;
    private boolean showGuiSecond = false;
    private boolean showFlyChat = false;
    private boolean showLoggedInChat = false;
    private boolean showClearLagChat = false;
    private boolean showTipsChat = false;
    private boolean showSaveChat = false;
    private boolean onSeichiClick;
    private boolean showGachaCountChat = false;
    private boolean showBuffChat = false;
    private boolean removeGiganticNameChat = false;
    private boolean showOtherGiganticHit = false;
    private boolean showGiganticHitChat = false;
    private boolean showCommonHitChat = false;
    //private int hitApollo = 0, hitIcarus = 0, hitNemesis = 0, hitHercules = 0, hitPluto = 0, hitThanatos = 0, hitGaea = 0, hitTitan = 0, hitArtemis = 0, hitArthur = 0;
    //private boolean inputGiganticNameChat = false;

    static {
        THREAD_POOL = Executors.newCachedThreadPool(new HaikuThreadFactory());
    }

    public static Haiku getInstance(){
        return instance;
    }

    public Minecraft getMc(){
        return this.mc;
    }

    @Mod.Metadata
    private static ModMetadata modMetadata;

    @Mod.EventHandler
    public void preInit(final FMLPreInitializationEvent event){
        loadMeta(modMetadata);
    }

    private void loadMeta(ModMetadata modMetadata){
        modMetadata.name = Reference.MOD_NAME;
        modMetadata.modId = Reference.MOD_ID;
        modMetadata.version = Reference.MOD_VERSION;
        modMetadata.authorList.add("uoken");
        modMetadata.description = "Type \"/haiku\" to open GUI.";
        modMetadata.url = "https://twitter.com/saduoken";
        modMetadata.autogenerated = false;
    }

    @Mod.EventHandler
    public void init(final FMLInitializationEvent event){
        instance = this;

        MinecraftForge.EVENT_BUS.register(this);

        ClientCommandHandler.instance.registerCommand(new HaikuCommand());

        MinecraftForge.EVENT_BUS.register(new HaikuListener());

        ConfigUtil.loadConfig();
    }

    @SubscribeEvent
    public void onClientTick(final TickEvent.ClientTickEvent event){
        if(this.showGui){
            this.mc.displayGuiScreen(new HaikuGuiScreen());

            this.showGui = false;
        }

        if(this.showGuiSecond){
            this.mc.displayGuiScreen(new HaikuGuiScreenSecond());

            this.showGuiSecond = false;
        }
    }

    @SubscribeEvent
    public void playerLoggedIn(final FMLNetworkEvent.ClientConnectedToServerEvent event){
        this.onSeichiClick = (!this.mc.isSingleplayer() && event.getManager().getRemoteAddress().toString().toLowerCase().contains("play.seichi.click"));
    }
    /*
    public String getStringRepresentation(final ArrayList<Character> list){
        StringBuilder builder = new StringBuilder(list.size());

        for(Character ch: list){
            builder.append(ch);
        }

        return builder.toString();
    }*/
    /*
    public void setHitApollo(int hitApollo){
        this.hitApollo = hitApollo;
    }

    public int getHitApollo(){
        return this.hitApollo;
    }

    public void setHitIcarus(int hitIcarus){
        this.hitIcarus = hitIcarus;
    }

    public int getHitIcarus(){
        return this.hitIcarus;
    }

    public void setHitNemesis(int hitNemesis){
        this.hitNemesis = hitNemesis;
    }

    public int getHitNemesis(){
        return this.hitNemesis;
    }

    public void setHitHercules(int hitHercules){
        this.hitHercules = hitHercules;
    }

    public int getHitHercules(){
        return this.hitHercules;
    }

    public void setHitPluto(int hitPluto){
        this.hitPluto = hitPluto;
    }

    public int getHitPluto(){
        return this.hitPluto;
    }

    public void setHitThanatos(int hitThanatos){
        this.hitThanatos = hitThanatos;
    }

    public int getHitThanatos(){
        return this.hitThanatos;
    }

    public void setHitGaea(int hitGaea){
        this.hitGaea = hitGaea;
    }

    public int getHitGaea(){
        return this.hitGaea;
    }

    public void setHitTitan(int hitTitan){
        this.hitTitan = hitTitan;
    }

    public int getHitTitan(){
        return this.hitTitan;
    }

    public void setHitArtemis(int hitArtemis){
        this.hitArtemis = hitArtemis;
    }

    public int getHitArtemis(){
        return this.hitArtemis;
    }

    public void setHitArthur(int hitArthur){
        this.hitArthur = hitArthur;
    }

    public int getHitArthur(){
        return this.hitArthur;
    }
    */
    public int getCountBuff(){
        return this.countBuff;
    }

    public void setCountBuff(int countBuff){
        this.countBuff = countBuff;
    }

    public int getCountRanking(){
        return this.countRanking;
    }

    public void setCountRanking(int countRanking){
        this.countRanking = countRanking;
    }

    public void setAddChatMessage(ITextComponent addChatMessage){
        this.addChatMessage = addChatMessage;
    }

    public ITextComponent getAddChatMessage(){
        return this.addChatMessage;
    }
    /*
    public void setInputGiganticNameChat(boolean inputNextLine){
        this.inputGiganticNameChat = inputNextLine;
    }

    public boolean isInputGiganticNameChat(){
        return this.inputGiganticNameChat;
    }
    */
    public boolean isShowBuffCounter() {
        return this.showBuffCounter;
    }

    public boolean isShowRankingCounter() {
        return this.showRankingCounter;
    }

    public void setShowBuffCounter(boolean showBuffCounter) {
        this.showBuffCounter = showBuffCounter;
    }

    public void setShowRankingCounter(boolean showRankingCounter) {
        this.showRankingCounter = showRankingCounter;
    }

    public void setShowGui(boolean showGui) {
        this.showGui = showGui;
    }

    public boolean isShowFlyChat() {
        return this.showFlyChat;
    }

    public boolean isShowLoggedInChat() {
        return this.showLoggedInChat;
    }

    public boolean isShowClearLagChat() {
        return this.showClearLagChat;
    }

    public void setShowFlyChat(boolean showFlyChat) {
        this.showFlyChat = showFlyChat;
    }

    public void setShowLoggedInChat(boolean showLoggedInChat) {
        this.showLoggedInChat = showLoggedInChat;
    }

    public void setShowClearLagChat(boolean showClearLagChat) {
        this.showClearLagChat = showClearLagChat;
    }

    public boolean isShowTipsChat() {
        return this.showTipsChat;
    }

    public void setShowTipsChat(boolean showTipsChat) {
        this.showTipsChat = showTipsChat;
    }

    public void setShowGuiSecond(boolean showGuiSecond) {
        this.showGuiSecond = showGuiSecond;
    }

    public boolean isSeichiClick() {
        return this.onSeichiClick;
    }

    public boolean isShowGachaCountChat(){
        return this.showGachaCountChat;
    }

    public void setShowGachaCountChat(boolean showGachaCountChat){
        this.showGachaCountChat = showGachaCountChat;
    }

    public boolean isShowBuffChat(){
        return this.showBuffChat;
    }

    public void setShowBuffChat(boolean showBuffChat){
        this.showBuffChat = showBuffChat;
    }

    public boolean isRemoveGiganticNameChat() {
        return this.removeGiganticNameChat;
    }

    public void setRemoveGiganticNameChat(boolean removeGiganticNameChat) {
        this.removeGiganticNameChat = removeGiganticNameChat;
    }

    public boolean isShowOtherGiganticHit() {
        return this.showOtherGiganticHit;
    }

    public void setShowOtherGiganticHit(boolean showOtherGiganticHit) {
        this.showOtherGiganticHit = showOtherGiganticHit;
    }

    public boolean isShowSaveChat() {
        return this.showSaveChat;
    }

    public void setShowSaveChat(boolean showSaveChat) {
        this.showSaveChat = showSaveChat;
    }

    public boolean isShowGiganticHitChat() {
        return this.showGiganticHitChat;
    }

    public void setShowGiganticHitChat(boolean giganticHitChat){
        this.showGiganticHitChat = giganticHitChat;
    }

    public boolean isShowCommonHitChat() {
        return this.showCommonHitChat;
    }

    public void setShowCommonHitChat(boolean showCommonHitChat) {
        this.showCommonHitChat = showCommonHitChat;
    }
}
